In [1]:
import pandas as pd

books = pd.read_csv("books_with_categories.csv")

In [8]:
from transformers import pipeline
classifier = pipeline("text-classification",
                      model="j-hartmann/emotion-english-distilroberta-base",
                      top_k = None,
                      device = -1)
classifier("I love this!")

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: j-hartmann/emotion-english-distilroberta-base
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

[[{'label': 'joy', 'score': 0.9771687984466553},
  {'label': 'surprise', 'score': 0.008528684265911579},
  {'label': 'neutral', 'score': 0.005764580797404051},
  {'label': 'anger', 'score': 0.004419785924255848},
  {'label': 'sadness', 'score': 0.002092391485348344},
  {'label': 'disgust', 'score': 0.001611991785466671},
  {'label': 'fear', 'score': 0.0004138525982853025}]]

In [4]:
books["description"][0]

'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.'

In [9]:
classifier(books["description"][0])

[[{'label': 'fear', 'score': 0.6548401713371277},
  {'label': 'neutral', 'score': 0.16985252499580383},
  {'label': 'sadness', 'score': 0.11640933156013489},
  {'label': 'surprise', 'score': 0.020700689405202866},
  {'label': 'disgust', 'score': 0.01910070702433586},
  {'label': 'joy', 'score': 0.015161466784775257},
  {'label': 'anger', 'score': 0.0039351508021354675}]]

In [10]:
classifier(books["description"][0].split("."))

[[{'label': 'surprise', 'score': 0.729602038860321},
  {'label': 'neutral', 'score': 0.14038604497909546},
  {'label': 'fear', 'score': 0.06816232949495316},
  {'label': 'joy', 'score': 0.04794265329837799},
  {'label': 'anger', 'score': 0.009156365878880024},
  {'label': 'disgust', 'score': 0.002628476358950138},
  {'label': 'sadness', 'score': 0.0021221654023975134}],
 [{'label': 'neutral', 'score': 0.44937023520469666},
  {'label': 'disgust', 'score': 0.27359169721603394},
  {'label': 'joy', 'score': 0.10908326506614685},
  {'label': 'sadness', 'score': 0.09362727403640747},
  {'label': 'anger', 'score': 0.040478333830833435},
  {'label': 'surprise', 'score': 0.026970140635967255},
  {'label': 'fear', 'score': 0.006879040505737066}],
 [{'label': 'neutral', 'score': 0.6462150812149048},
  {'label': 'sadness', 'score': 0.24273402988910675},
  {'label': 'disgust', 'score': 0.04342275485396385},
  {'label': 'surprise', 'score': 0.028300579637289047},
  {'label': 'joy', 'score': 0.014211492612957954},
  {'label': 'fear', 'score': 0.014084121212363243},
  {'label': 'anger', 'score': 0.011031919158995152}],
 [{'label': 'fear', 'score': 0.9281682372093201},
  {'label': 'anger', 'score': 0.032190948724746704},
  {'label': 'neutral', 'score': 0.012808676809072495},
  {'label': 'sadness', 'score': 0.008756890892982483},
  {'label': 'surprise', 'score': 0.008597920648753643},
  {'label': 'disgust', 'score': 0.00843182671815157},
  {'label': 'joy', 'score': 0.0010455843294039369}],
 [{'label': 'sadness', 'score': 0.9671575427055359},
  {'label': 'neutral', 'score': 0.015104148536920547},
  {'label': 'disgust', 'score': 0.006480589509010315},
  {'label': 'fear', 'score': 0.005393982399255037},
  {'label': 'surprise', 'score': 0.0022869398817420006},
  {'label': 'anger', 'score': 0.0018428886542096734},
  {'label': 'joy', 'score': 0.0017338779289275408}],
 [{'label': 'joy', 'score': 0.9327982664108276},
  {'label': 'disgust', 'score': 0.03771696984767914},
  {'label': 'neutral', 'score': 0.015891820192337036},
  {'label': 'sadness', 'score': 0.006444491911679506},
  {'label': 'anger', 'score': 0.005024959798902273},
  {'label': 'surprise', 'score': 0.0015812052879482508},
  {'label': 'fear', 'score': 0.0005423057591542602}],
 [{'label': 'joy', 'score': 0.6528702974319458},
  {'label': 'neutral', 'score': 0.25427523255348206},
  {'label': 'surprise', 'score': 0.06808295845985413},
  {'label': 'sadness', 'score': 0.009909001179039478},
  {'label': 'disgust', 'score': 0.006512224208563566},
  {'label': 'anger', 'score': 0.004821314010769129},
  {'label': 'fear', 'score': 0.0035290182568132877}],
 [{'label': 'neutral', 'score': 0.5494767427444458},
  {'label': 'sadness', 'score': 0.11169017851352692},
  {'label': 'disgust', 'score': 0.10400670766830444},
  {'label': 'surprise', 'score': 0.07876548916101456},
  {'label': 'anger', 'score': 0.0641336441040039},
  {'label': 'fear', 'score': 0.05136282369494438},
  {'label': 'joy', 'score': 0.0405644066631794}]]

In [11]:
sentences = books["description"][0].split(".")
predictions = classifier(sentences)

In [12]:
sentences[0]

'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives'

In [13]:
predictions[0]

[{'label': 'surprise', 'score': 0.729602038860321},
 {'label': 'neutral', 'score': 0.14038604497909546},
 {'label': 'fear', 'score': 0.06816232949495316},
 {'label': 'joy', 'score': 0.04794265329837799},
 {'label': 'anger', 'score': 0.009156365878880024},
 {'label': 'disgust', 'score': 0.002628476358950138},
 {'label': 'sadness', 'score': 0.0021221654023975134}]

In [14]:
sentences[3]

' Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist'

In [15]:
predictions[3]

[{'label': 'fear', 'score': 0.9281682372093201},
 {'label': 'anger', 'score': 0.032190948724746704},
 {'label': 'neutral', 'score': 0.012808676809072495},
 {'label': 'sadness', 'score': 0.008756890892982483},
 {'label': 'surprise', 'score': 0.008597920648753643},
 {'label': 'disgust', 'score': 0.00843182671815157},
 {'label': 'joy', 'score': 0.0010455843294039369}]

In [16]:
sorted(predictions[0], key=lambda x: x["label"])

[{'label': 'anger', 'score': 0.009156365878880024},
 {'label': 'disgust', 'score': 0.002628476358950138},
 {'label': 'fear', 'score': 0.06816232949495316},
 {'label': 'joy', 'score': 0.04794265329837799},
 {'label': 'neutral', 'score': 0.14038604497909546},
 {'label': 'sadness', 'score': 0.0021221654023975134},
 {'label': 'surprise', 'score': 0.729602038860321}]

In [17]:
import numpy as np

emotion_labels = ["anger", "disgust", "fear", "joy", "sadness", "surprise", "neutral"]
isbn = []
emotion_scores = {label : [] for label in emotion_labels}

def calculate_max_emotion_scores(predictions):
    per_emotion_scores = {label: [] for label in emotion_labels}

    for prediction in predictions:
        sorted_predictions = sorted(prediction, key=lambda x: x["label"])
        for index, label in enumerate(emotion_labels):
            per_emotion_scores[label].append(sorted_predictions[index]["score"])
    return {label: np.max(scores) for label, scores in per_emotion_scores.items()}

In [18]:
for i in range(10):
    isbn.append(books["isbn13"][i])
    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)
    max_scores = calculate_max_emotion_scores(predictions)
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

In [19]:
emotion_scores

{'anger': [np.float64(0.0641336441040039),
  np.float64(0.6126199960708618),
  np.float64(0.0641336441040039),
  np.float64(0.3514844477176666),
  np.float64(0.08141247928142548),
  np.float64(0.23222437500953674),
  np.float64(0.5381838083267212),
  np.float64(0.0641336441040039),
  np.float64(0.3006701171398163),
  np.float64(0.0641336441040039)],
 'disgust': [np.float64(0.27359169721603394),
  np.float64(0.3482848107814789),
  np.float64(0.10400670766830444),
  np.float64(0.15072225034236908),
  np.float64(0.18449555337429047),
  np.float64(0.727175235748291),
  np.float64(0.155854731798172),
  np.float64(0.10400670766830444),
  np.float64(0.2794811725616455),
  np.float64(0.1779259592294693)],
 'fear': [np.float64(0.9281682372093201),
  np.float64(0.9425276517868042),
  np.float64(0.9723207950592041),
  np.float64(0.360706090927124),
  np.float64(0.09504348784685135),
  np.float64(0.05136282369494438),
  np.float64(0.7474274635314941),
  np.float64(0.4044972062110901),
  np.float64(0.9155241250991821),
  np.float64(0.05136282369494438)],
 'joy': [np.float64(0.9327982664108276),
  np.float64(0.704422116279602),
  np.float64(0.7672374844551086),
  np.float64(0.2518811523914337),
  np.float64(0.0405644066631794),
  np.float64(0.043375834822654724),
  np.float64(0.8725653886795044),
  np.float64(0.0405644066631794),
  np.float64(0.0405644066631794),
  np.float64(0.0405644066631794)],
 'sadness': [np.float64(0.6462150812149048),
  np.float64(0.8879395127296448),
  np.float64(0.5494767427444458),
  np.float64(0.7326849102973938),
  np.float64(0.8843895196914673),
  np.float64(0.621391773223877),
  np.float64(0.71219402551651),
  np.float64(0.5494767427444458),
  np.float64(0.8402893543243408),
  np.float64(0.8603723645210266)],
 'surprise': [np.float64(0.9671575427055359),
  np.float64(0.11169017851352692),
  np.float64(0.11169017851352692),
  np.float64(0.11169017851352692),
  np.float64(0.47587984800338745),
  np.float64(0.11169017851352692),
  np.float64(0.40800127387046814),
  np.float64(0.8202818036079407),
  np.float64(0.3544616997241974),
  np.float64(0.11169017851352692)],
 'neutral': [np.float64(0.729602038860321),
  np.float64(0.2525465786457062),
  np.float64(0.07876548916101456),
  np.float64(0.07876548916101456),
  np.float64(0.07876548916101456),
  np.float64(0.2719036638736725),
  np.float64(0.07876548916101456),
  np.float64(0.23448671400547028),
  np.float64(0.13561373949050903),
  np.float64(0.07876548916101456)]}

In [20]:
from tqdm import tqdm


emotion_labels = ["anger", "disgust", "fear", "joy", "sadness", "surprise", "neutral"]
isbn = []
emotion_scores = {label : [] for label in emotion_labels}

for i in tqdm(range(len(books))):
    isbn.append(books["isbn13"][i])
    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)
    max_scores = calculate_max_emotion_scores(predictions)
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

  0%|          | 0/5197 [00:00<?, ?it/s]
  0%|          | 1/5197 [00:00<54:06,  1.60it/s]
  0%|          | 2/5197 [00:01<45:48,  1.89it/s]
  0%|          | 3/5197 [00:01<30:34,  2.83it/s]
  0%|          | 4/5197 [00:01<24:07,  3.59it/s]
  0%|          | 5/5197 [00:01<23:20,  3.71it/s]
  0%|          | 6/5197 [00:01<20:21,  4.25it/s]
  0%|          | 7/5197 [00:02<26:08,  3.31it/s]
  0%|          | 8/5197 [00:02<20:59,  4.12it/s]
  0%|          | 9/5197 [00:02<22:12,  3.89it/s]
  0%|          | 10/5197 [00:02<19:13,  4.50it/s]
  0%|          | 11/5197 [00:02<17:46,  4.86it/s]
  0%|          | 12/5197 [00:03<23:05,  3.74it/s]
  0%|          | 13/5197 [00:03<26:35,  3.25it/s]
  0%|          | 14/5197 [00:04<28:35,  3.02it/s]
  0%|          | 15/5197 [00:04<25:38,  3.37it/s]
  0%|          | 16/5197 [00:04<20:37,  4.19it/s]
  0%|          | 18/5197 [00:04<14:30,  5.95it/s]
  0%|          | 19/5197 [00:04<15:22,  5.61it/s]
  0%|          | 20/5197 [00:05<17:13,  5.01it/s]
  0%|          | 21/5197 [00:05<15:54,  5.43it/s]
  0%|          | 22/5197 [00:05<14:21,  6.00it/s]
  0%|          | 24/5197 [00:05<12:43,  6.78it/s]
  0%|          | 25/5197 [00:05<14:59,  5.75it/s]
  1%|          | 26/5197 [00:06<17:49,  4.84it/s]
  1%|          | 27/5197 [00:06<16:18,  5.28it/s]
  1%|          | 28/5197 [00:06<15:26,  5.58it/s]
  1%|          | 30/5197 [00:06<18:11,  4.73it/s]
  1%|          | 31/5197 [00:07<19:16,  4.47it/s]
  1%|          | 32/5197 [00:07<18:39,  4.61it/s]
  1%|          | 33/5197 [00:07<17:53,  4.81it/s]
  1%|          | 34/5197 [00:07<19:54,  4.32it/s]
  1%|          | 35/5197 [00:08<17:02,  5.05it/s]
  1%|          | 36/5197 [00:08<19:37,  4.38it/s]
  1%|          | 37/5197 [00:08<23:01,  3.73it/s]
  1%|          | 38/5197 [00:09<24:08,  3.56it/s]
  1%|          | 40/5197 [00:09<16:49,  5.11it/s]
  1%|          | 41/5197 [00:09<18:30,  4.64it/s]
  1%|          | 42/5197 [00:09<22:14,  3.86it/s]
  1%|          | 43/5197 [00:10<23:12,  3.70it/s]
  1%|          | 44/5197 [00:10<21:02,  4.08it/s]
  1%|          | 45/5197 [00:10<19:30,  4.40it/s]
  1%|          | 46/5197 [00:10<22:13,  3.86it/s]
  1%|          | 47/5197 [00:11<21:04,  4.07it/s]
  1%|          | 48/5197 [00:11<22:37,  3.79it/s]
  1%|          | 49/5197 [00:12<32:41,  2.62it/s]
  1%|          | 50/5197 [00:12<27:50,  3.08it/s]
  1%|          | 51/5197 [00:12<24:24,  3.52it/s]
  1%|          | 52/5197 [00:12<22:38,  3.79it/s]
  1%|          | 53/5197 [00:12<19:47,  4.33it/s]
  1%|          | 54/5197 [00:13<21:18,  4.02it/s]
  1%|          | 55/5197 [00:13<21:01,  4.07it/s]
  1%|          | 56/5197 [00:13<17:43,  4.84it/s]
  1%|          | 57/5197 [00:13<15:13,  5.63it/s]
  1%|          | 58/5197 [00:13<13:19,  6.43it/s]
  1%|          | 59/5197 [00:14<24:42,  3.47it/s]
  1%|          | 60/5197 [00:14<20:12,  4.24it/s]
  1%|          | 61/5197 [00:14<19:56,  4.29it/s]
  1%|          | 62/5197 [00:14<16:46,  5.10it/s]
  1%|          | 63/5197 [00:14<18:28,  4.63it/s]
  1%|          | 64/5197 [00:15<21:33,  3.97it/s]
  1%|▏         | 65/5197 [00:15<22:29,  3.80it/s]
  1%|▏         | 66/5197 [00:15<19:28,  4.39it/s]
  1%|▏         | 67/5197 [00:15<18:40,  4.58it/s]
  1%|▏         | 68/5197 [00:16<21:11,  4.03it/s]
  1%|▏         | 69/5197 [00:16<24:17,  3.52it/s]
  1%|▏         | 70/5197 [00:16<21:54,  3.90it/s]
  1%|▏         | 71/5197 [00:17<34:34,  2.47it/s]
  1%|▏         | 72/5197 [00:17<32:51,  2.60it/s]
  1%|▏         | 73/5197 [00:18<35:16,  2.42it/s]
  1%|▏         | 74/5197 [00:18<31:50,  2.68it/s]
  1%|▏         | 75/5197 [00:18<25:09,  3.39it/s]
  1%|▏         | 76/5197 [00:19<29:00,  2.94it/s]
  1%|▏         | 77/5197 [00:19<28:09,  3.03it/s]
  2%|▏         | 78/5197 [00:19<23:04,  3.70it/s]
  2%|▏         | 79/5197 [00:19<23:50,  3.58it/s]
  2%|▏         | 80/5197 [00:20<21:29,  3.97it/s]
  2%|▏         | 81/5197 [00:20<19:58,  4.27it/s]
  2%|▏         | 83/5197 [00:20<17:06,  4.98it/s]
  2%|▏         | 84/5197 [00:21<23:59,  3.55it/s]
  2%|▏         | 86/5197 [00:21<16:38,  5.12it/s]
  2%|▏         | 87/5197 [00:21<17:14,  4.94it/s]
  2%|▏         | 88/5197 [00:21<19:19,  4.41it/s]
  2%|▏         | 90/5197 [00:22<15:08,  5.62it/s]
  2%|▏         | 91/5197 [00:22<17:23,  4.89it/s]
  2%|▏         | 92/5197 [00:22<23:22,  3.64it/s]
  2%|▏         | 93/5197 [00:23<30:06,  2.83it/s]
  2%|▏         | 94/5197 [00:24<44:15,  1.92it/s]
  2%|▏         | 95/5197 [00:24<35:01,  2.43it/s]
  2%|▏         | 97/5197 [00:24<25:04,  3.39it/s]
  2%|▏         | 98/5197 [00:25<25:46,  3.30it/s]
  2%|▏         | 99/5197 [00:25<23:11,  3.66it/s]
  2%|▏         | 100/5197 [00:25<23:54,  3.55it/s]
  2%|▏         | 102/5197 [00:26<21:27,  3.96it/s]
  2%|▏         | 104/5197 [00:26<22:04,  3.85it/s]
  2%|▏         | 105/5197 [00:27<25:43,  3.30it/s]
  2%|▏         | 106/5197 [00:27<23:25,  3.62it/s]
  2%|▏         | 107/5197 [00:27<23:45,  3.57it/s]
  2%|▏         | 108/5197 [00:27<25:44,  3.29it/s]
  2%|▏         | 109/5197 [00:28<25:14,  3.36it/s]
  2%|▏         | 110/5197 [00:28<22:15,  3.81it/s]
  2%|▏         | 111/5197 [00:28<18:48,  4.51it/s]
  2%|▏         | 112/5197 [00:28<18:27,  4.59it/s]
  2%|▏         | 113/5197 [00:29<24:28,  3.46it/s]
  2%|▏         | 114/5197 [00:29<23:57,  3.54it/s]
  2%|▏         | 115/5197 [00:29<24:56,  3.40it/s]
  2%|▏         | 116/5197 [00:29<20:45,  4.08it/s]
  2%|▏         | 117/5197 [00:30<19:43,  4.29it/s]
  2%|▏         | 118/5197 [00:30<18:06,  4.68it/s]
  2%|▏         | 119/5197 [00:30<20:11,  4.19it/s]
  2%|▏         | 120/5197 [00:30<19:23,  4.36it/s]
  2%|▏         | 121/5197 [00:31<19:18,  4.38it/s]
  2%|▏         | 122/5197 [00:31<31:42,  2.67it/s]
  2%|▏         | 123/5197 [00:31<28:18,  2.99it/s]
  2%|▏         | 124/5197 [00:32<34:57,  2.42it/s]
  2%|▏         | 125/5197 [00:32<33:08,  2.55it/s]
  2%|▏         | 126/5197 [00:33<28:50,  2.93it/s]
  2%|▏         | 127/5197 [00:33<28:27,  2.97it/s]
  2%|▏         | 128/5197 [00:33<25:18,  3.34it/s]
  2%|▏         | 129/5197 [00:34<27:56,  3.02it/s]
  3%|▎         | 130/5197 [00:34<22:38,  3.73it/s]
  3%|▎         | 131/5197 [00:34<23:47,  3.55it/s]
  3%|▎         | 132/5197 [00:34<20:48,  4.06it/s]
  3%|▎         | 133/5197 [00:34<21:32,  3.92it/s]
  3%|▎         | 134/5197 [00:35<25:21,  3.33it/s]
  3%|▎         | 135/5197 [00:35<27:36,  3.06it/s]
  3%|▎         | 136/5197 [00:36<29:08,  2.89it/s]
  3%|▎         | 137/5197 [00:36<23:52,  3.53it/s]
  3%|▎         | 138/5197 [00:37<38:47,  2.17it/s]
  3%|▎         | 139/5197 [00:37<31:15,  2.70it/s]
  3%|▎         | 140/5197 [00:37<25:10,  3.35it/s]
  3%|▎         | 142/5197 [00:37<16:40,  5.05it/s]
  3%|▎         | 143/5197 [00:37<16:19,  5.16it/s]
  3%|▎         | 144/5197 [00:37<14:18,  5.89it/s]
  3%|▎         | 145/5197 [00:38<13:32,  6.22it/s]
  3%|▎         | 146/5197 [00:38<19:57,  4.22it/s]
  3%|▎         | 147/5197 [00:38<25:07,  3.35it/s]
  3%|▎         | 148/5197 [00:39<23:37,  3.56it/s]
  3%|▎         | 149/5197 [00:39<22:50,  3.68it/s]
  3%|▎         | 150/5197 [00:39<30:51,  2.73it/s]
  3%|▎         | 151/5197 [00:40<30:48,  2.73it/s]
  3%|▎         | 152/5197 [00:40<26:40,  3.15it/s]
  3%|▎         | 153/5197 [00:40<21:57,  3.83it/s]
  3%|▎         | 154/5197 [00:40<20:42,  4.06it/s]
  3%|▎         | 155/5197 [00:41<23:05,  3.64it/s]
  3%|▎         | 156/5197 [00:41<21:19,  3.94it/s]
  3%|▎         | 157/5197 [00:41<20:48,  4.04it/s]
  3%|▎         | 159/5197 [00:41<17:06,  4.91it/s]
  3%|▎         | 161/5197 [00:42<19:31,  4.30it/s]
  3%|▎         | 162/5197 [00:43<24:01,  3.49it/s]
  3%|▎         | 163/5197 [00:43<29:39,  2.83it/s]
  3%|▎         | 164/5197 [00:43<30:32,  2.75it/s]
  3%|▎         | 165/5197 [00:44<33:06,  2.53it/s]
  3%|▎         | 166/5197 [00:44<27:25,  3.06it/s]
  3%|▎         | 167/5197 [00:45<29:50,  2.81it/s]
  3%|▎         | 168/5197 [00:45<30:11,  2.78it/s]
  3%|▎         | 169/5197 [00:45<24:06,  3.48it/s]
  3%|▎         | 170/5197 [00:45<27:44,  3.02it/s]
  3%|▎         | 171/5197 [00:46<28:52,  2.90it/s]
  3%|▎         | 172/5197 [00:46<33:33,  2.50it/s]
  3%|▎         | 173/5197 [00:47<43:34,  1.92it/s]
  3%|▎         | 174/5197 [00:48<39:50,  2.10it/s]
  3%|▎         | 175/5197 [00:48<35:01,  2.39it/s]
  3%|▎         | 176/5197 [00:48<35:43,  2.34it/s]
  3%|▎         | 177/5197 [00:48<28:30,  2.94it/s]
  3%|▎         | 178/5197 [00:49<23:15,  3.60it/s]
  3%|▎         | 179/5197 [00:49<19:55,  4.20it/s]
  3%|▎         | 180/5197 [00:49<28:16,  2.96it/s]

model.safetensors:   0%|          | 0.00/329M [00:00<?, ?B/s]

  3%|▎         | 181/5197 [00:50<37:17,  2.24it/s]
  4%|▎         | 182/5197 [00:50<34:01,  2.46it/s]
  4%|▎         | 183/5197 [00:51<37:05,  2.25it/s]
  4%|▎         | 184/5197 [00:51<32:10,  2.60it/s]
  4%|▎         | 185/5197 [00:52<37:32,  2.23it/s]
  4%|▎         | 186/5197 [00:52<41:11,  2.03it/s]
  4%|▎         | 187/5197 [00:52<31:25,  2.66it/s]
  4%|▎         | 188/5197 [00:53<28:57,  2.88it/s]
  4%|▎         | 189/5197 [00:53<26:00,  3.21it/s]
  4%|▎         | 190/5197 [00:53<23:28,  3.55it/s]
  4%|▎         | 191/5197 [00:53<19:23,  4.30it/s]
  4%|▎         | 192/5197 [00:53<21:24,  3.90it/s]
  4%|▎         | 193/5197 [00:54<20:45,  4.02it/s]
  4%|▎         | 194/5197 [00:54<24:21,  3.42it/s]
  4%|▍         | 195/5197 [00:54<22:35,  3.69it/s]
  4%|▍         | 196/5197 [00:55<25:36,  3.26it/s]
  4%|▍         | 197/5197 [00:55<31:31,  2.64it/s]
  4%|▍         | 198/5197 [00:55<25:07,  3.32it/s]
  4%|▍         | 199/5197 [00:56<33:48,  2.46it/s]
  4%|▍         | 200/5197 [00:56<31:02,  2.68it/s]
  4%|▍         | 201/5197 [00:57<29:05,  2.86it/s]
  4%|▍         | 202/5197 [00:57<26:54,  3.09it/s]
  4%|▍         | 203/5197 [00:57<23:26,  3.55it/s]
  4%|▍         | 204/5197 [00:57<22:40,  3.67it/s]
  4%|▍         | 205/5197 [00:58<23:50,  3.49it/s]
  4%|▍         | 206/5197 [00:58<23:17,  3.57it/s]
  4%|▍         | 207/5197 [00:58<24:23,  3.41it/s]
  4%|▍         | 208/5197 [00:58<19:53,  4.18it/s]
  4%|▍         | 209/5197 [00:58<17:31,  4.74it/s]
  4%|▍         | 210/5197 [00:59<18:01,  4.61it/s]
  4%|▍         | 211/5197 [00:59<18:49,  4.42it/s]
  4%|▍         | 212/5197 [00:59<16:31,  5.03it/s]
  4%|▍         | 213/5197 [00:59<17:24,  4.77it/s]
  4%|▍         | 214/5197 [01:00<16:28,  5.04it/s]
  4%|▍         | 215/5197 [01:00<22:14,  3.73it/s]
  4%|▍         | 216/5197 [01:00<23:54,  3.47it/s]
  4%|▍         | 217/5197 [01:00<19:25,  4.27it/s]
  4%|▍         | 218/5197 [01:01<19:51,  4.18it/s]
  4%|▍         | 219/5197 [01:01<19:51,  4.18it/s]
  4%|▍         | 221/5197 [01:01<13:58,  5.94it/s]
  4%|▍         | 222/5197 [01:01<18:47,  4.41it/s]
  4%|▍         | 223/5197 [01:02<25:00,  3.31it/s]
  4%|▍         | 224/5197 [01:02<22:49,  3.63it/s]
  4%|▍         | 225/5197 [01:02<22:07,  3.74it/s]
  4%|▍         | 226/5197 [01:03<20:57,  3.95it/s]
  4%|▍         | 227/5197 [01:03<21:42,  3.82it/s]
  4%|▍         | 228/5197 [01:03<22:06,  3.75it/s]
  4%|▍         | 229/5197 [01:03<20:15,  4.09it/s]
  4%|▍         | 230/5197 [01:03<16:50,  4.91it/s]
  4%|▍         | 231/5197 [01:04<19:03,  4.34it/s]
  4%|▍         | 232/5197 [01:04<20:31,  4.03it/s]
  5%|▍         | 234/5197 [01:04<15:03,  5.49it/s]
  5%|▍         | 235/5197 [01:04<15:32,  5.32it/s]
  5%|▍         | 236/5197 [01:05<26:20,  3.14it/s]
  5%|▍         | 237/5197 [01:05<22:46,  3.63it/s]
  5%|▍         | 238/5197 [01:06<21:40,  3.81it/s]
  5%|▍         | 239/5197 [01:06<20:00,  4.13it/s]
  5%|▍         | 240/5197 [01:06<20:25,  4.04it/s]
  5%|▍         | 241/5197 [01:06<22:31,  3.67it/s]
  5%|▍         | 242/5197 [01:07<19:57,  4.14it/s]
  5%|▍         | 244/5197 [01:07<15:30,  5.32it/s]
  5%|▍         | 245/5197 [01:07<16:20,  5.05it/s]
  5%|▍         | 246/5197 [01:07<14:37,  5.64it/s]
  5%|▍         | 248/5197 [01:07<14:17,  5.77it/s]
  5%|▍         | 249/5197 [01:08<25:23,  3.25it/s]
  5%|▍         | 250/5197 [01:09<27:39,  2.98it/s]
  5%|▍         | 251/5197 [01:09<24:00,  3.43it/s]
  5%|▍         | 252/5197 [01:09<28:14,  2.92it/s]
  5%|▍         | 253/5197 [01:10<29:24,  2.80it/s]
  5%|▍         | 254/5197 [01:10<24:05,  3.42it/s]
  5%|▍         | 255/5197 [01:10<20:38,  3.99it/s]
  5%|▍         | 256/5197 [01:10<24:24,  3.37it/s]
  5%|▍         | 258/5197 [01:11<16:53,  4.87it/s]
  5%|▍         | 259/5197 [01:11<26:49,  3.07it/s]
  5%|▌         | 260/5197 [01:11<22:38,  3.63it/s]
  5%|▌         | 261/5197 [01:12<29:59,  2.74it/s]
  5%|▌         | 262/5197 [01:12<29:46,  2.76it/s]
  5%|▌         | 263/5197 [01:13<30:31,  2.69it/s]
  5%|▌         | 264/5197 [01:13<24:20,  3.38it/s]
  5%|▌         | 265/5197 [01:13<24:38,  3.34it/s]
  5%|▌         | 266/5197 [01:14<26:54,  3.05it/s]
  5%|▌         | 268/5197 [01:14<19:09,  4.29it/s]
  5%|▌         | 269/5197 [01:14<19:04,  4.31it/s]
  5%|▌         | 270/5197 [01:14<22:24,  3.66it/s]
  5%|▌         | 272/5197 [01:15<16:10,  5.08it/s]
  5%|▌         | 273/5197 [01:15<15:19,  5.36it/s]
  5%|▌         | 274/5197 [01:15<13:43,  5.98it/s]
  5%|▌         | 275/5197 [01:15<19:17,  4.25it/s]
  5%|▌         | 276/5197 [01:16<23:09,  3.54it/s]
  5%|▌         | 278/5197 [01:16<20:34,  3.99it/s]
  5%|▌         | 279/5197 [01:16<18:29,  4.43it/s]
  5%|▌         | 281/5197 [01:16<13:18,  6.16it/s]
  5%|▌         | 283/5197 [01:17<10:52,  7.53it/s]
  5%|▌         | 284/5197 [01:17<13:10,  6.22it/s]
  5%|▌         | 285/5197 [01:17<14:46,  5.54it/s]
  6%|▌         | 286/5197 [01:17<15:23,  5.32it/s]
  6%|▌         | 288/5197 [01:18<13:26,  6.08it/s]
  6%|▌         | 289/5197 [01:18<12:36,  6.49it/s]
  6%|▌         | 290/5197 [01:18<12:26,  6.58it/s]
  6%|▌         | 291/5197 [01:18<16:48,  4.86it/s]
  6%|▌         | 292/5197 [01:18<15:02,  5.43it/s]
  6%|▌         | 293/5197 [01:19<16:16,  5.02it/s]
  6%|▌         | 294/5197 [01:19<17:05,  4.78it/s]
  6%|▌         | 295/5197 [01:19<17:21,  4.71it/s]
  6%|▌         | 296/5197 [01:19<22:52,  3.57it/s]
  6%|▌         | 297/5197 [01:20<21:51,  3.74it/s]
  6%|▌         | 299/5197 [01:20<21:20,  3.82it/s]
  6%|▌         | 300/5197 [01:20<18:26,  4.42it/s]
  6%|▌         | 301/5197 [01:20<16:07,  5.06it/s]
  6%|▌         | 302/5197 [01:21<18:10,  4.49it/s]
  6%|▌         | 303/5197 [01:21<16:11,  5.04it/s]
  6%|▌         | 304/5197 [01:21<16:44,  4.87it/s]
  6%|▌         | 305/5197 [01:21<17:42,  4.60it/s]
  6%|▌         | 306/5197 [01:21<16:34,  4.92it/s]
  6%|▌         | 307/5197 [01:22<17:42,  4.60it/s]
  6%|▌         | 308/5197 [01:22<16:20,  4.99it/s]
  6%|▌         | 309/5197 [01:22<17:36,  4.62it/s]
  6%|▌         | 310/5197 [01:22<19:04,  4.27it/s]
  6%|▌         | 311/5197 [01:23<17:42,  4.60it/s]
  6%|▌         | 312/5197 [01:23<17:30,  4.65it/s]
  6%|▌         | 313/5197 [01:23<21:54,  3.72it/s]
  6%|▌         | 314/5197 [01:24<30:42,  2.65it/s]
  6%|▌         | 315/5197 [01:24<28:56,  2.81it/s]
  6%|▌         | 316/5197 [01:25<30:34,  2.66it/s]
  6%|▌         | 317/5197 [01:25<27:29,  2.96it/s]
  6%|▌         | 318/5197 [01:25<25:07,  3.24it/s]
  6%|▌         | 319/5197 [01:25<27:25,  2.96it/s]
  6%|▌         | 321/5197 [01:26<22:30,  3.61it/s]
  6%|▌         | 322/5197 [01:26<20:25,  3.98it/s]
  6%|▌         | 323/5197 [01:26<20:36,  3.94it/s]
  6%|▌         | 324/5197 [01:27<19:56,  4.07it/s]
  6%|▋         | 325/5197 [01:27<18:11,  4.46it/s]
  6%|▋         | 326/5197 [01:27<15:27,  5.25it/s]
  6%|▋         | 327/5197 [01:27<13:39,  5.94it/s]
  6%|▋         | 328/5197 [01:27<18:06,  4.48it/s]
  6%|▋         | 329/5197 [01:27<15:33,  5.22it/s]
  6%|▋         | 330/5197 [01:28<14:00,  5.79it/s]
  6%|▋         | 331/5197 [01:28<15:25,  5.26it/s]
  6%|▋         | 333/5197 [01:28<13:01,  6.22it/s]
  6%|▋         | 334/5197 [01:28<12:53,  6.29it/s]
  6%|▋         | 336/5197 [01:28<10:12,  7.93it/s]
  6%|▋         | 337/5197 [01:29<12:09,  6.66it/s]
  7%|▋         | 338/5197 [01:29<12:07,  6.68it/s]
  7%|▋         | 339/5197 [01:29<12:08,  6.66it/s]
  7%|▋         | 340/5197 [01:29<13:42,  5.90it/s]
  7%|▋         | 341/5197 [01:30<28:49,  2.81it/s]
  7%|▋         | 342/5197 [01:30<28:03,  2.88it/s]
  7%|▋         | 343/5197 [01:31<27:25,  2.95it/s]
  7%|▋         | 344/5197 [01:31<25:55,  3.12it/s]
  7%|▋         | 346/5197 [01:31<19:59,  4.05it/s]
  7%|▋         | 347/5197 [01:31<19:48,  4.08it/s]
  7%|▋         | 348/5197 [01:32<24:06,  3.35it/s]
  7%|▋         | 349/5197 [01:32<20:33,  3.93it/s]
  7%|▋         | 351/5197 [01:32<18:14,  4.43it/s]
  7%|▋         | 352/5197 [01:33<18:34,  4.35it/s]
  7%|▋         | 354/5197 [01:33<17:25,  4.63it/s]
  7%|▋         | 355/5197 [01:33<18:03,  4.47it/s]
  7%|▋         | 356/5197 [01:34<19:32,  4.13it/s]
  7%|▋         | 357/5197 [01:34<20:26,  3.95it/s]
  7%|▋         | 358/5197 [01:34<20:40,  3.90it/s]
  7%|▋         | 359/5197 [01:34<21:01,  3.84it/s]
  7%|▋         | 361/5197 [01:35<17:22,  4.64it/s]
  7%|▋         | 362/5197 [01:35<16:30,  4.88it/s]
  7%|▋         | 363/5197 [01:35<16:43,  4.82it/s]
  7%|▋         | 364/5197 [01:35<16:57,  4.75it/s]
  7%|▋         | 365/5197 [01:35<17:02,  4.73it/s]
  7%|▋         | 366/5197 [01:36<20:11,  3.99it/s]
  7%|▋         | 367/5197 [01:36<24:50,  3.24it/s]
  7%|▋         | 368/5197 [01:37<24:03,  3.35it/s]
  7%|▋         | 369/5197 [01:37<24:46,  3.25it/s]
  7%|▋         | 370/5197 [01:37<24:35,  3.27it/s]
  7%|▋         | 371/5197 [01:37<22:16,  3.61it/s]
  7%|▋         | 372/5197 [01:38<22:12,  3.62it/s]
  7%|▋         | 373/5197 [01:38<19:01,  4.23it/s]
  7%|▋         | 374/5197 [01:38<20:22,  3.95it/s]
  7%|▋         | 375/5197 [01:39<24:39,  3.26it/s]
  7%|▋         | 376/5197 [01:39<21:07,  3.80it/s]
  7%|▋         | 377/5197 [01:39<21:33,  3.73it/s]
  7%|▋         | 378/5197 [01:39<17:48,  4.51it/s]
  7%|▋         | 379/5197 [01:40<24:04,  3.34it/s]
  7%|▋         | 380/5197 [01:40<21:06,  3.80it/s]
  7%|▋         | 381/5197 [01:40<27:44,  2.89it/s]
  7%|▋         | 382/5197 [01:40<22:48,  3.52it/s]
  7%|▋         | 383/5197 [01:41<21:29,  3.73it/s]
  7%|▋         | 384/5197 [01:41<18:38,  4.30it/s]
  7%|▋         | 385/5197 [01:41<20:36,  3.89it/s]
  7%|▋         | 386/5197 [01:41<20:09,  3.98it/s]
  7%|▋         | 387/5197 [01:42<20:30,  3.91it/s]
  7%|▋         | 388/5197 [01:42<18:59,  4.22it/s]
  7%|▋         | 389/5197 [01:42<16:56,  4.73it/s]
  8%|▊         | 391/5197 [01:42<14:29,  5.53it/s]
  8%|▊         | 392/5197 [01:43<19:21,  4.14it/s]
  8%|▊         | 393/5197 [01:43<18:45,  4.27it/s]
  8%|▊         | 394/5197 [01:43<15:52,  5.04it/s]
  8%|▊         | 395/5197 [01:43<16:26,  4.87it/s]
  8%|▊         | 397/5197 [01:43<12:30,  6.40it/s]
  8%|▊         | 398/5197 [01:44<11:41,  6.84it/s]
  8%|▊         | 399/5197 [01:44<17:28,  4.58it/s]
  8%|▊         | 400/5197 [01:44<17:23,  4.60it/s]
  8%|▊         | 401/5197 [01:44<15:09,  5.28it/s]
  8%|▊         | 402/5197 [01:45<18:43,  4.27it/s]
  8%|▊         | 403/5197 [01:45<20:10,  3.96it/s]
  8%|▊         | 404/5197 [01:45<16:47,  4.76it/s]
  8%|▊         | 405/5197 [01:45<17:46,  4.49it/s]
  8%|▊         | 406/5197 [01:46<20:37,  3.87it/s]
  8%|▊         | 407/5197 [01:46<23:21,  3.42it/s]
  8%|▊         | 408/5197 [01:46<23:46,  3.36it/s]
  8%|▊         | 409/5197 [01:47<22:29,  3.55it/s]
  8%|▊         | 410/5197 [01:47<19:14,  4.15it/s]
  8%|▊         | 411/5197 [01:47<15:53,  5.02it/s]
  8%|▊         | 412/5197 [01:47<14:33,  5.48it/s]
  8%|▊         | 413/5197 [01:47<14:25,  5.53it/s]
  8%|▊         | 414/5197 [01:47<18:28,  4.31it/s]
  8%|▊         | 415/5197 [01:48<16:30,  4.83it/s]
  8%|▊         | 416/5197 [01:48<23:26,  3.40it/s]
  8%|▊         | 417/5197 [01:48<23:46,  3.35it/s]
  8%|▊         | 418/5197 [01:49<20:05,  3.96it/s]
  8%|▊         | 419/5197 [01:49<22:11,  3.59it/s]
  8%|▊         | 420/5197 [01:49<18:49,  4.23it/s]
  8%|▊         | 421/5197 [01:49<20:53,  3.81it/s]
  8%|▊         | 422/5197 [01:50<17:23,  4.57it/s]
  8%|▊         | 423/5197 [01:50<15:43,  5.06it/s]
  8%|▊         | 424/5197 [01:50<23:33,  3.38it/s]
  8%|▊         | 425/5197 [01:50<19:10,  4.15it/s]
  8%|▊         | 426/5197 [01:51<19:15,  4.13it/s]
  8%|▊         | 427/5197 [01:51<21:02,  3.78it/s]
  8%|▊         | 428/5197 [01:51<22:49,  3.48it/s]
  8%|▊         | 429/5197 [01:51<20:30,  3.87it/s]
  8%|▊         | 430/5197 [01:52<18:32,  4.29it/s]
  8%|▊         | 431/5197 [01:52<29:18,  2.71it/s]
  8%|▊         | 432/5197 [01:52<23:26,  3.39it/s]
  8%|▊         | 433/5197 [01:53<19:55,  3.99it/s]
  8%|▊         | 434/5197 [01:53<20:38,  3.85it/s]
  8%|▊         | 435/5197 [01:53<21:03,  3.77it/s]
  8%|▊         | 436/5197 [01:54<26:38,  2.98it/s]
  8%|▊         | 437/5197 [01:54<27:00,  2.94it/s]
  8%|▊         | 438/5197 [01:54<29:02,  2.73it/s]
  8%|▊         | 439/5197 [01:55<27:27,  2.89it/s]
  8%|▊         | 440/5197 [01:55<33:02,  2.40it/s]
  8%|▊         | 441/5197 [01:56<37:52,  2.09it/s]
  9%|▊         | 442/5197 [01:56<29:23,  2.70it/s]
  9%|▊         | 443/5197 [01:57<41:34,  1.91it/s]
  9%|▊         | 444/5197 [01:57<32:13,  2.46it/s]
  9%|▊         | 445/5197 [01:57<25:13,  3.14it/s]
  9%|▊         | 446/5197 [01:57<26:47,  2.95it/s]
  9%|▊         | 447/5197 [01:59<52:23,  1.51it/s]
  9%|▊         | 448/5197 [01:59<40:50,  1.94it/s]
  9%|▊         | 449/5197 [02:00<42:20,  1.87it/s]
  9%|▊         | 450/5197 [02:00<36:02,  2.19it/s]
  9%|▊         | 451/5197 [02:00<28:17,  2.80it/s]
  9%|▊         | 452/5197 [02:00<23:00,  3.44it/s]
  9%|▊         | 453/5197 [02:01<26:43,  2.96it/s]
  9%|▊         | 454/5197 [02:01<23:58,  3.30it/s]
  9%|▉         | 455/5197 [02:01<27:28,  2.88it/s]
  9%|▉         | 456/5197 [02:02<27:28,  2.88it/s]
  9%|▉         | 458/5197 [02:02<20:26,  3.86it/s]
  9%|▉         | 459/5197 [02:02<21:48,  3.62it/s]
  9%|▉         | 460/5197 [02:03<22:44,  3.47it/s]
  9%|▉         | 461/5197 [02:03<24:03,  3.28it/s]
  9%|▉         | 462/5197 [02:03<23:08,  3.41it/s]
  9%|▉         | 463/5197 [02:03<19:52,  3.97it/s]
  9%|▉         | 464/5197 [02:04<18:13,  4.33it/s]
  9%|▉         | 465/5197 [02:04<23:03,  3.42it/s]
  9%|▉         | 466/5197 [02:04<22:57,  3.44it/s]
  9%|▉         | 467/5197 [02:05<22:04,  3.57it/s]
  9%|▉         | 468/5197 [02:05<21:27,  3.67it/s]
  9%|▉         | 469/5197 [02:05<20:22,  3.87it/s]
  9%|▉         | 470/5197 [02:05<17:28,  4.51it/s]
  9%|▉         | 471/5197 [02:07<45:56,  1.71it/s]
  9%|▉         | 472/5197 [02:07<37:14,  2.11it/s]
  9%|▉         | 473/5197 [02:07<34:18,  2.30it/s]
  9%|▉         | 474/5197 [02:07<28:58,  2.72it/s]
  9%|▉         | 475/5197 [02:08<27:35,  2.85it/s]
  9%|▉         | 476/5197 [02:08<34:38,  2.27it/s]
  9%|▉         | 477/5197 [02:09<31:10,  2.52it/s]
  9%|▉         | 478/5197 [02:09<34:49,  2.26it/s]
  9%|▉         | 479/5197 [02:09<28:15,  2.78it/s]
  9%|▉         | 480/5197 [02:10<24:29,  3.21it/s]
  9%|▉         | 481/5197 [02:10<26:44,  2.94it/s]
  9%|▉         | 482/5197 [02:11<32:42,  2.40it/s]
  9%|▉         | 483/5197 [02:11<27:51,  2.82it/s]
  9%|▉         | 484/5197 [02:11<24:42,  3.18it/s]
  9%|▉         | 485/5197 [02:11<22:18,  3.52it/s]
  9%|▉         | 486/5197 [02:11<21:42,  3.62it/s]
  9%|▉         | 487/5197 [02:12<18:16,  4.30it/s]
  9%|▉         | 488/5197 [02:12<19:22,  4.05it/s]
  9%|▉         | 489/5197 [02:12<17:24,  4.51it/s]
  9%|▉         | 490/5197 [02:12<17:49,  4.40it/s]
  9%|▉         | 491/5197 [02:12<16:07,  4.86it/s]
  9%|▉         | 492/5197 [02:13<19:32,  4.01it/s]
  9%|▉         | 493/5197 [02:13<21:33,  3.64it/s]
 10%|▉         | 494/5197 [02:13<19:15,  4.07it/s]
 10%|▉         | 495/5197 [02:14<21:49,  3.59it/s]
 10%|▉         | 496/5197 [02:14<19:37,  3.99it/s]
 10%|▉         | 498/5197 [02:14<15:31,  5.05it/s]
 10%|▉         | 499/5197 [02:14<15:02,  5.21it/s]
 10%|▉         | 500/5197 [02:14<13:56,  5.61it/s]
 10%|▉         | 501/5197 [02:15<16:27,  4.76it/s]
 10%|▉         | 502/5197 [02:15<17:35,  4.45it/s]
 10%|▉         | 503/5197 [02:15<17:55,  4.36it/s]
 10%|▉         | 504/5197 [02:15<19:09,  4.08it/s]
 10%|▉         | 505/5197 [02:16<15:58,  4.90it/s]
 10%|▉         | 506/5197 [02:16<15:07,  5.17it/s]
 10%|▉         | 507/5197 [02:16<16:55,  4.62it/s]
 10%|▉         | 508/5197 [02:16<17:17,  4.52it/s]
 10%|▉         | 509/5197 [02:16<16:58,  4.60it/s]
 10%|▉         | 510/5197 [02:17<19:36,  3.98it/s]
 10%|▉         | 511/5197 [02:17<17:57,  4.35it/s]
 10%|▉         | 512/5197 [02:17<16:46,  4.66it/s]
 10%|▉         | 514/5197 [02:18<15:23,  5.07it/s]
 10%|▉         | 515/5197 [02:18<16:52,  4.62it/s]
 10%|▉         | 516/5197 [02:18<16:34,  4.71it/s]
 10%|▉         | 517/5197 [02:18<15:06,  5.16it/s]
 10%|▉         | 518/5197 [02:18<13:31,  5.77it/s]
 10%|▉         | 519/5197 [02:18<14:26,  5.40it/s]
 10%|█         | 520/5197 [02:19<13:46,  5.66it/s]
 10%|█         | 521/5197 [02:19<12:52,  6.06it/s]
 10%|█         | 522/5197 [02:19<12:40,  6.15it/s]
 10%|█         | 523/5197 [02:19<13:04,  5.96it/s]
 10%|█         | 524/5197 [02:19<16:00,  4.86it/s]
 10%|█         | 525/5197 [02:20<17:50,  4.36it/s]
 10%|█         | 526/5197 [02:20<16:04,  4.84it/s]
 10%|█         | 527/5197 [02:20<22:33,  3.45it/s]
 10%|█         | 528/5197 [02:21<21:27,  3.63it/s]
 10%|█         | 529/5197 [02:21<28:43,  2.71it/s]
 10%|█         | 530/5197 [02:22<50:32,  1.54it/s]
 10%|█         | 531/5197 [02:24<1:09:24,  1.12it/s]
 10%|█         | 532/5197 [02:24<57:59,  1.34it/s]
 10%|█         | 533/5197 [02:25<58:46,  1.32it/s]
 10%|█         | 534/5197 [02:26<55:47,  1.39it/s]
 10%|█         | 535/5197 [02:26<55:37,  1.40it/s]
 10%|█         | 536/5197 [02:27<50:37,  1.53it/s]
 10%|█         | 537/5197 [02:27<47:46,  1.63it/s]
 10%|█         | 538/5197 [02:28<54:21,  1.43it/s]
 10%|█         | 539/5197 [02:29<48:05,  1.61it/s]
 10%|█         | 540/5197 [02:30<1:08:53,  1.13it/s]
 10%|█         | 541/5197 [02:31<59:23,  1.31it/s]
 10%|█         | 542/5197 [02:31<55:01,  1.41it/s]
 10%|█         | 543/5197 [02:32<53:50,  1.44it/s]
 10%|█         | 544/5197 [02:33<49:19,  1.57it/s]
 10%|█         | 545/5197 [02:34<59:17,  1.31it/s]
 11%|█         | 546/5197 [02:34<44:10,  1.75it/s]
 11%|█         | 547/5197 [02:34<38:52,  1.99it/s]
 11%|█         | 548/5197 [02:34<29:57,  2.59it/s]
 11%|█         | 549/5197 [02:35<49:07,  1.58it/s]
 11%|█         | 550/5197 [02:36<50:42,  1.53it/s]
 11%|█         | 551/5197 [02:37<1:00:14,  1.29it/s]
 11%|█         | 552/5197 [02:37<46:39,  1.66it/s]
 11%|█         | 553/5197 [02:38<48:15,  1.60it/s]
 11%|█         | 554/5197 [02:39<55:16,  1.40it/s]
 11%|█         | 555/5197 [02:40<56:54,  1.36it/s]
 11%|█         | 556/5197 [02:41<1:13:24,  1.05it/s]
 11%|█         | 557/5197 [02:42<1:07:17,  1.15it/s]
 11%|█         | 558/5197 [02:42<54:06,  1.43it/s]
 11%|█         | 559/5197 [02:43<46:58,  1.65it/s]
 11%|█         | 560/5197 [02:43<51:34,  1.50it/s]
 11%|█         | 562/5197 [02:44<39:14,  1.97it/s]
 11%|█         | 563/5197 [02:44<35:30,  2.18it/s]
 11%|█         | 564/5197 [02:45<34:54,  2.21it/s]
 11%|█         | 565/5197 [02:45<35:25,  2.18it/s]
 11%|█         | 566/5197 [02:46<33:06,  2.33it/s]
 11%|█         | 567/5197 [02:46<34:53,  2.21it/s]
 11%|█         | 568/5197 [02:46<31:55,  2.42it/s]
 11%|█         | 569/5197 [02:47<36:46,  2.10it/s]
 11%|█         | 570/5197 [02:48<43:15,  1.78it/s]
 11%|█         | 571/5197 [02:48<33:19,  2.31it/s]
 11%|█         | 572/5197 [02:49<38:48,  1.99it/s]
 11%|█         | 573/5197 [02:49<43:22,  1.78it/s]
 11%|█         | 574/5197 [02:50<57:01,  1.35it/s]
 11%|█         | 575/5197 [02:51<42:57,  1.79it/s]
 11%|█         | 576/5197 [02:51<35:22,  2.18it/s]
 11%|█         | 577/5197 [02:52<41:50,  1.84it/s]
 11%|█         | 578/5197 [02:52<39:20,  1.96it/s]
 11%|█         | 579/5197 [02:52<37:30,  2.05it/s]
 11%|█         | 580/5197 [02:53<35:55,  2.14it/s]
 11%|█         | 581/5197 [02:53<35:41,  2.16it/s]
 11%|█         | 582/5197 [02:54<32:36,  2.36it/s]
 11%|█         | 583/5197 [02:54<30:08,  2.55it/s]
 11%|█         | 584/5197 [02:54<27:10,  2.83it/s]
 11%|█▏        | 586/5197 [02:55<20:23,  3.77it/s]
 11%|█▏        | 587/5197 [02:55<18:58,  4.05it/s]
 11%|█▏        | 588/5197 [02:55<18:58,  4.05it/s]
 11%|█▏        | 589/5197 [02:55<16:17,  4.71it/s]
 11%|█▏        | 590/5197 [02:55<14:07,  5.44it/s]
 11%|█▏        | 591/5197 [02:55<16:27,  4.66it/s]
 11%|█▏        | 593/5197 [02:56<12:21,  6.21it/s]
 11%|█▏        | 594/5197 [02:56<11:19,  6.77it/s]
 11%|█▏        | 596/5197 [02:56<09:54,  7.74it/s]
 11%|█▏        | 597/5197 [02:56<11:01,  6.95it/s]
 12%|█▏        | 598/5197 [02:56<11:34,  6.62it/s]
 12%|█▏        | 599/5197 [02:57<11:18,  6.78it/s]

In [21]:
emotions_df = pd.DataFrame(emotion_scores)
emotions_df["isbn13"] = isbn

In [22]:
emotions_df

,anger,disgust,fear,joy,sadness,surprise,neutral,isbn13
0,0.064134,0.273592,0.928168,0.932798,0.646215,0.967158,0.729602,9780002005883
1,0.612620,0.348285,0.942528,0.704422,0.887940,0.111690,0.252547,9780002261982
2,0.064134,0.104007,0.972321,0.767237,0.549477,0.111690,0.078765,9780006178736
3,0.351484,0.150722,0.360706,0.251881,0.732685,0.111690,0.078765,9780006280897
4,0.081412,0.184496,0.095043,0.040564,0.884390,0.475880,0.078765,9780006280934
...,...,...,...,...,...,...,...,...
5192,0.148209,0.030643,0.919165,0.255172,0.853721,0.980877,0.030656,9788172235222
5193,0.064134,0.114383,0.051363,0.400263,0.883198,0.111690,0.227765,9788173031014
5194,0.009997,0.009929,0.339218,0.947779,0.375755,0.066685,0.057625,9788179921623
5195,0.064134,0.104007,0.459270,0.759457,0.951104,0.368111,0.078765,9788185300535
5196,0.064134,0.104007,0.051363,0.958549,0.915193,0.111690,0.078765,9789027712059

In [23]:
books = pd.merge(books, emotions_df, on = "isbn13" )

In [24]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,...,title_and_subtitle,tagged_description,simple_categories,anger,disgust,fear,joy,sadness,surprise,neutral
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,...,Gilead,9780002005883 A NOVEL THAT READERS and critics...,Fiction,0.064134,0.273592,0.928168,0.932798,0.646215,0.967158,0.729602
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,...,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,Fiction,0.612620,0.348285,0.942528,0.704422,0.887940,0.111690,0.252547
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,...,Rage of angels,"9780006178736 A memorable, mesmerizing heroine...",Fiction,0.064134,0.104007,0.972321,0.767237,0.549477,0.111690,0.078765
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,...,The Four Loves,9780006280897 Lewis' work on the nature of lov...,Nonfiction,0.351484,0.150722,0.360706,0.251881,0.732685,0.111690,0.078765
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,...,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le...",Nonfiction,0.081412,0.184496,0.095043,0.040564,0.884390,0.475880,0.078765
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,...,Mistaken Identity,9788172235222 On A Train Journey Home To North...,Fiction,0.148209,0.030643,0.919165,0.255172,0.853721,0.980877,0.030656
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,...,Journey to the East,9788173031014 This book tells the tale of a ma...,Nonfiction,0.064134,0.114383,0.051363,0.400263,0.883198,0.111690,0.227765
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,...,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...,Fiction,0.009997,0.009929,0.339218,0.947779,0.375755,0.066685,0.057625
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,...,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...,Nonfiction,0.064134,0.104007,0.459270,0.759457,0.951104,0.368111,0.078765
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,...,The Berlin Phenomenology,9789027712059 Since the three volume edition o...,Nonfiction,0.064134,0.104007,0.051363,0.958549,0.915193,0.111690,0.078765

In [25]:
books.to_csv("books_with_emotions.csv", index = False)